version: "3.7"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack
    hostname: localstack
    networks:
      - localstack-net
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - ./data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d
  postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: "curtis"
      POSTGRES_PASSWORD: "house"
      POSTGRES_DB: "monsterhouse"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/initdb.d/init_databases.sql:/docker-entrypoint-initdb.d/003_init_databases.sql
networks:
  localstack-net:
    external: false
    driver: bridge
    name: localstack-net