package tagger

const (
	tagAPIURL     = "https://api.imagga.com/v2/tags"
	successStatus = "success"
)

// This is the response object we get from the Imagga API
// This struct was auto-generated by json-to-go: https://mholt.github.io/json-to-go/
type TagResponse struct {
	Result struct {
		Tags []struct {
			Confidence float64 `json:"confidence"`
			Tag        struct {
				En string `json:"en"`
			} `json:"tag"`
		} `json:"tags"`
	} `json:"result"`
	Status struct {
		Text string `json:"text"`
		Type string `json:"type"`
	} `json:"status"`
}
